  --////////////////////////////////////////////////////////////////////////

  CREATE TYPE NUMBERTABLE AS TABLE OF NUMBER;

  --///////////////// Replace "SCHEMA" with the database user /////////////

  CREATE TABLE "SCHEMA"."ATL" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BEGIN" NUMBER(*,0) NOT NULL ENABLE, 
	"END" NUMBER(*,0) NOT NULL ENABLE, 
	"LABEL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "ATL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("BEGIN") 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("END") 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("LABEL") ;

  CREATE INDEX "SCHEMA"."B" ON "SCHEMA"."ATL" ("BEGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "SCHEMA"."E" ON "SCHEMA"."ATL" ("END") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  --////////////////////////////////////////////////////////////////////////
 
  CREATE TABLE "SCHEMA"."B" 
   (	"B" NUMBER(*,0) NOT NULL ENABLE, 
	"L" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "B_PK" PRIMARY KEY ("B", "L")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("B") 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("L") ;

  --////////////////////////////////////////////////////////////////////////
    
  CREATE TABLE "SCHEMA"."NOT_B" 
   (	"B" NUMBER(*,0) NOT NULL ENABLE, 
	"L" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "NOT_B_PK" PRIMARY KEY ("B", "L")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("B") 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("L") ;

  --////////////////////////////////////////////////////////////////////////
  
  CREATE TABLE "SCHEMA"."R" 
   (	"E" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "R_PK" PRIMARY KEY ("E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("E") ;

  --////////////////////////////////////////////////////////////////////////
 
  CREATE TABLE "SCHEMA"."NOT_R" 
   (	"E" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "NOT_R_PK" PRIMARY KEY ("E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW 
  DISTRIBUTE AUTO NO DUPLICATE 
  INMEMORY MEMCOMPRESS FOR QUERY LOW ("E") ;

  --////////////////////////////////////////////////////////////////////////

  CREATE OR REPLACE FUNCTION ATL_CHECKER (model IN CLOB, length IN NUMBER, response IN OUT CLOB) RETURN VARCHAR2 AS
  LANGUAGE JAVA NAME 'ATLChecker.checkModel(oracle.sql.CLOB, int, oracle.sql.CLOB[]) 
  RETURN java.lang.String';

	